interface MahabharatType {
  id: number;
  paravName: string;
  Story: string;
}

export type { MahabharatType };

const Mahabharat: MahabharatType[] = [
  {
    id: 1,
    paravName: "Origin from Chandravansh to Kuruvansh",
    Story:
      "According to the Puranas , Atri was born from Lord Brahma , Moon was born from Atri , Mercury was born from Moon and Ilanandan Pururava was born from Mercury. From Pururava were born Ayu, from Ayu King Nahusha and from Nahusha Yayati . He was born from Yayati . Bharat was born in Puru's lineage and King Kuru was born in Bharat's family. Shantanu was born in the lineage of Kuru . Ganganandan Bhishma was born from Shantanu . He had two younger brothers – Chitrangada and Vichitravirya . He was born from Shantanu 's womb to Satyavati . After Shantanu went to heaven , Bhishma remained unmarried and followed the rule of his brother Vichitravirya. Chitrangad was killed in his childhood by a Gandharva named Chitrangad . Then Bhishma defeated the opposition in the battle and brought back the three daughters of Kashiraj – Amba , Ambika and Ambalika . Both of them were the daughters of Vichitravirya. After some time, King Vichitravirya suffered from Rajyakshma and passed away. Then with the permission of Satyavati, King Dhritarashtra was born from Ambika's womb and Pandu was born from Ambalika's womb through Niyoga by Vyasji. Dhritarashtra got hundred sons from Gandhari's womb, of which Duryodhana was the eldest and Pandu had five sons like Yudhishtar , Bhima , Arjun , Nakul , Sahadev etc.",
  },
  {
    id: 2,
    paravName: "Pandu's kingdom consecration",
    Story: `Dhritarashtra was blind since birth, hence Pandu was made the king in his place, due to this Dhritarashtra always got angry at his blindness and started feeling hatred towards Pandu. Pandu conquered the whole of India and expanded the boundaries of the Kuru kingdom to the country of the Yavanas. Once King Pandu went to the forest for hunting with his two wives – Kunti and Madri. There he saw a mating pair of deer. Pandu immediately injured the deer with his arrow. Dying, the innocent sage in the form of a deer cursed Pandu,"King! There will be no man in this world as cruel as you. You have shot me with an arrow during sexual intercourse, so whenever you engage in sexual intercourse, you will die."Pandu became very sad due to this curse and said to his queens, "O ladies! Now I will give up all my desires and stay in this forest only. You all go back to Hastinapur." Hearing his words, both the queens felt sad and said, " Nath! We cannot survive without you even for a moment. Please keep us with you in the forest." Pandu accepted his request and allowed him to live with him in the forest. Meanwhile, on the day of Amavasya, King Pandu saw sages going for darshan of Lord Brahma. He requested those sages to take him along. On his request, the sages and sages said, "King! No childless man has the right to go to Brahmalok, hence we are unable to take you with us." After listening to the sages and sages, Pandu said to his wife, " O Kunti! My very birth is becoming futile because a childless person cannot get rid of his debt to his ancestors, debt to sages, debt to gods and debt to humans. Can you help me in getting a son?" Kunti said, "O son of Arya! Sage Durvasa has given me such a mantra by which I can invoke any god and get the desired thing. You order which god I should invoke." On this Pandu ordered to invite Dharma. Dharma blessed Kunti with a son who was named Yudhishthir. Later, Pandu ordered Kunti to invite Vayudev and Indradev twice again. Bhima was born from Vayudev and Arjun was born from Indra. Thereafter, with the permission of Pandu, Kunti initiated Madri into that mantra. Madri invited the Ashvanikumars and Nakul and Sahadev were born. One day King Pandu was traveling with Madri in the forest on the banks of a river. The atmosphere was very pleasant and a cool, mild and fragrant breeze was blowing. Suddenly Madri's clothes were blown away by the gust of wind. Due to this, Pandu's mind became restless and he was about to engage in sexual intercourse when he died due to the curse. Madri committed sati with him but Kunti returned to Hastinapur to raise her sons. The sages living there left the Pandavas in the palace and on the advice of the sages and Kunti, everyone accepted the Pandavas as their sons and welcomed them.`,
  },
  {
    id: 3,
    paravName: "Birth of Karna, Lakshagraha Conspiracy and Draupadi Swayamvar",
    Story: `When Kunti was not married, Karna was born from her womb (from the Sun 's part) . But fearing public shame, Kunti locked Karna in a box and floated him in the river Ganga. While Karna was floating in the river Ganga, Maharaja Dhritarashtra's charioteer Adhiratha and his wife Radha saw him and adopted him and brought him up. Started following. Since his childhood, Karna was more interested in the art of war rather than in chariot driving like his father Adhiratha. Karna and his father Adhiratha met Acharya Drona, who was one of the best masters of the art of warfare at that time. Dronacharya used to teach Kuru princes at that time. He refused to give education to Karna because Karna was a charioteer's son and Drona used to give education only to Kshatriyas. After Dronacharya's disagreement, Karna contacted Parashurama who used to teach only Brahmins. Karna claimed to be a Brahmin and requested for education from Parashurama. Parashurama accepted Karna's request and made Karna adept in the art of warfare and archery like himself. In this way Karna became a very hard-working and skillful disciple of Parashurama. Karna lived under the shelter of Duryodhana . Due to divine fortune and Shakuni's deceit, the fire of enmity between the Kauravas and the Pandavas was ignited. Duryodhana was a man of very flawed intellect. At the behest of Shakuni, he tried to kill the Pandavas several times in his childhood. When Yudhishthira, who was superior to him in qualities, was made the crown prince after attaining youth, Shakuni kept the Pandavas in the house built by Laksh and tried to burn them by setting fire to them, but with the help of Vidur, all five Pandavas along with their mother were saved from the burning house. Went out. From there he went to Ekachakra city and started living in the house of a Brahmin in the guise of a sage. Then, after killing the demon named Bak, on the advice of Vyas ji, he went to Panchal kingdom , where Draupadi 's swayamvara was going to take place. In the kingdom of Panchal, due to Arjun's ability to hit the target, when Matsya was killed, the five Pandavas got Draupadi as their wife.`,
  },
  {
    id: 4,
    paravName: "Establishment of Indraprastha ",
    Story: `Before the Swayamvara, Draupadi started considering all the Pandavas except Vidur as dead and due to this, Dhritarashtra made Duryodhana the crown prince on the advice of Shakuni. After Draupadi Swayamvar, Duryodhana etc. came to know that Pandavas were alive. The Pandavas asked for their kingdom from the Kauravas, but to avoid the crisis of civil war, Yudhishtra received the ruined Khandava forest given by the Kauravas as half of his kingdom. Pandukumar Arjun along with Shri Krishna burnt the Khandava forest and satisfied the fire by stopping the rain caused by Indra with his (umbrella-shaped) dam of arrows. There Arjun and Krishna defeated all the gods in the war. As a result, Arjun received the divine Gandiva bow and the perfect chariot from Agnidev and Krishna ji received the Sudarshan Chakra. He met Lord Krishna-like charioteer in the war and received divine weapons like Brahmastra and indestructible arrows from Acharya Drona. Indra was very happy to see the bravery of his son Arjun. At the behest of Indra, the divine architect Vishwakarma and the demon Maya together built the Khandava forest into a city as grand as Indrapuri, which was named Indraprastha.`,
  },
  {
    id: 5,
    paravName: "Pandavas' world conquest and their exile",
    Story: `All the Pandavas were proficient in all types of knowledge. Pandavas conquered all the directions and Yudhishthir started ruling. He performed the ritual of Rajasuya Yagya filled with abundant gold . This splendor of his became unbearable for Duryodhana. Taking Shakuni with him on the advice of his brother Dushasana and his famous friend Karna , he indulged in gambling in the gambling session and laughingly won over Yudhishthira , his brothers, Draupadi and their kingdom through deceit and gambling. Duryodhana insulted Draupadi a lot in the Kuru Rajya Sabha and tried to disrobe her. Shri Krishna saved her shame and then Draupadi was about to curse everyone but Gandhari came and stopped this from happening. After being defeated in gambling, Yudhishthir went to the forest with his brothers. There he spent twelve years as per his promise. In the forest too, like before, he used to feed food to majority of Brahmins every day. (One day he) satisfied Durvasa (by the grace of Shri Krishna) along with eighty thousand Dwijas. There he was accompanied by his wife Draupadi and priest Dhaumyaji.

    After completing his twelfth year, he went to Virat Nagar . There Yudhishthir remained unknown to everyone and started living as a Brahmin named 'Kank'. Bhimsen had become a cook. Arjun named himself ' Brihannala '. Pandava wife Draupadi started living in the palace as Sairandhri. Similarly, Nakul- Sahdev also changed their names. Bhimsen killed Keechak who wanted to take away the chastity of Draupadi during the night. Thereafter, Kauravas started taking away Virat's cows, then Arjun defeated them. At that time, Kauravas recognised the Pandavas. Shri Krishna's sister Subhadra gave birth to a son named Abhimanyu from Arjun. King Virat gave his daughter Uttara in marriage to him.`,
  },
  {
    id: 6,
    paravName:
      "Peace messenger Shri Krishna, beginning of war and Shri Krishna's sermon to Arjun ",
    Story: `Dharmaraj Yudhishthir, being the master of seven Akshauhini army, got ready to fight with the Kauravas. First Lord Shri Krishna went as a messenger to the most angry Duryodhana. He said to King Duryodhana, the lord of the eleven Akshauhini armies –

    'King! You give half the kingdom to Yudhishthir or offer him only five villages; Otherwise fight with them.
    
    Hearing Shri Krishna's words, Duryodhana said - 'I will not give them even land equal to the tip of a needle; Yes, I will definitely fight with them.
    
    Saying this he got ready to capture Lord Krishna. At that time, in the royal court, Lord Shri Krishna frightened Duryodhana by giving him the darshan of his most ferocious world form. Then Vidur took him to his home and worshiped and honored the Lord.
    
    Thereafter he returned to Yudhishthir and said - 'Maharaj! You fight with Duryodhana'
    
    The armies of Yudhishthir and Duryodhana advanced on the field of Kurukshetra . Seeing the teachers like Grandfather Bhishma and Acharya Drona in opposition to him , Arjun turned away from the war, then Lord Shri Krishna said to him - "Partha! Gurus like Bhishma and others are not worthy of mourning. Man's body is perishable, but the soul can never be destroyed." It would happen. This soul itself is Parabrahma.
    
    'I am Brahma' - this is how you understand that soul. Remain equanimous in success and failure of work, take refuge in Karmayoga and follow Kshatradharma."
    
    On hearing this from Shri Krishna, Arjun mounted his chariot and started the war. He blew the conch. Grandfather Bhishma was the first commander in Duryodhana's army. The commander of Pandavas was Shikhandi . A huge war broke out between these two. In that war, the warriors of the Kaurava side including Bhishma started attacking the soldiers of the Pandava side and the warriors of the Pandava side like Shikhandi etc. started targeting the Kaurava soldiers with their arrows.
    That war between the Kaurava and Pandava armies seemed like a battle between the gods and demons. That war seemed very enjoyable to the gods standing in the sky and watching . Bhishma fought for ten days and killed most of the Pandavas' army with his arrows.`,
  },
  {
    id: 7,
    paravName: "Bhishma kills Drona",
    Story: `On the tenth day, Arjun showered heavy arrows on brave Bhishma. Here, with the inspiration of Drupada , Shikhandi also fired a volley of arrows at Bhishma like a cloud that rains water. Elephants, horsemen, charioteers and footmen on both sides were killed by each other's arrows. Bhishma's death was under his will. When the Pandavas understood that they could not win this war with Bhishma present, then on the suggestion of Shri Krishna, they asked Bhishma Pitamah for the solution to his death. He said that as long as I have a weapon in my hand, no one except Mahadev can defeat me. It was he who gave the suggestion to the Pandavas. Shikhandi was Amba in her previous birth, hence he considered her to be a daughter. On the 10th day of the war, Arjun made Shikhandi sit in front of his chariot. Seeing Shikhandi ahead, Bhishma released his bow. After he gave up his weapons, Arjun made him sleep on a bed of arrows. They started spending time meditating and praising Lord Vishnu while waiting for Uttarayan. When Duryodhana became distraught with grief after Bhishma fell on his arrow-bed, Acharya Drona assumed the responsibility of commander. On the other hand, Dhrishtadyumna became the commander in the army of the rejoicing Pandavas. There was a fierce war between them, which increased the population of Yamalok. Kings like Virat and Drupada drowned in the ocean in the form of Drona. At that time Drona looked like Kaal. Just then a voice came to his ears that 'Ashwatthama has been killed'. On hearing this, Acharya Drona gave up his weapons . At such a time, he fell on the earth after being hit by the arrows of Dhrishtadyumna.`,
  },
  {
    id: 8,
    paravName: "Karna and surgical decapitation",
    Story:
      "Dron was very tough. He was killed on the fifth day after destroying all the Kshatriyas. Duryodhana was again overcome with grief. At that time Karna became the commander of his army. Arjuna got the control of Pandava army. There was a terrible battle between Karna and Arjun involving various types of weapons, which was going to defeat the battle of Devasura badly. In the battle between Karna and Arjun, Karna killed many warriors of the enemy side with his arrows; Although the battle was becoming a stalemate, Karna got into trouble when one of the wheels of his chariot sank into the earth (due to the curse of Mother Earth). He becomes unable to even use the divine weapons given to him, as was the curse of his Guru Parashurama. Then Karna comes down to remove the wheel of his chariot and requests Arjun to stop shooting arrows at him for some time, following the rules of war. Then Shri Krishna tells Arjun that Karna has no right to talk about war rules and religion now, whereas he himself had not followed any war rules and religion at the time of killing Abhimanyu. He further said that where had his religion gone when he had called the divine-born Draupadi a prostitute in front of the entire Kuru royal assembly. Where had his religion gone in the gaming hall? Therefore, now he has no right to talk about any religion or war rules and he told Arjun that now Karna is helpless (Brahmin's curse was fruitful) so he should kill him. Shri Krishna says that if Arjun does not kill Karna now at this crucial juncture, then Pandavas will probably never be able to kill him and this war will never be won. Then, Arjuna beheaded Karna using a divine weapon. After Karna's body fell on the ground, a light emerged from Karna's body and merged into the Sun. Subsequently, King Shalya became the commander of the Kaurava army, but he could last only half a day in the war. By noon, King Yudhishthir killed him.",
  },
  {
    id: 9,
    paravName: "Duryodhana's killing and end of Mahabharata war ",
    Story: `Dropped. Almost the entire army of Duryodhana was killed in the war. Ultimately he had a fight with Bhimsen. He attacked Bhimsen after killing many infantrymen of the Pandava side. At that time, Duryodhana's other younger brothers were also killed by Bhimsen while attacking with his mace. On that eighteenth day of the Mahabharata war, during the night, the mighty Ashwatthama put the sleeping Akshauhini army of Pandavas to sleep forever. He did not even leave alive Draupadi's five sons, his Panchaladeshi brothers and Dhrishtadyumna. Draupadi started crying childless. Then Arjun defeated Ashwatthama with a straw weapon and took out the gem from his head. (Seeing him being killed, Draupadi saved his life by pleading him). Ashwatthama Despite all this, the evil Ashwatthama used a weapon on Uttara to destroy her womb. That womb was almost burnt by his weapon; But Lord Shri Krishna gave him life again. The same fetus of Uttara later became famous by the name of King Parikshit. Kritavarma, Kripacharya and Ashwatthama – these three Kaurava side heroes survived that battle. On the other hand, only five Pandavas , Satyaki and Lord Shri Krishna could survive; No one else was left. At that time, the cry of orphan women was spreading everywhere. Yudhishthir went with Bhimsen and other brothers and consoled them and after cremating all the heroes killed in the battlefield, offered water for them and donated money etc. Thereafter, Yudhishthir went to Shantanunandan Bhishma, who was seated on a bed in Kurukshetra, and heard from him all the peaceful dharma, Rajdharma (Apadharma), Moksha Dharma and Daanadharma. Then he sat on the throne. After this, that Shatrumardan king performed Ashwamedha Yagya and donated a lot of money to the Brahmins. Subsequently , after returning from Dwarka , Arjun fought against each other due to the curse received due to the massacre. Hearing the news of the massacre of the Yadavas, Yudhishthir placed Parikshit on the king's throne and after making a grand departure with his brothers, he reached heaven.`,
  },
  {
    id: 10,
    paravName: "Destruction of Yadukul and departure of Pandavas",
    Story: `When Yudhishthir ascended the throne, Dhritarashtra entered the Vanaprastha Ashram from Grihastha Ashram and went to the forest. Or after passing from one ashram of sages to another, he went to the forest. Goddess Gandhari and Pritha (Kunti) were also with him . May Vidur ji burn with fire and go to heaven. In this way, Lord Vishnu lifted the burden of the earth and killed the demons etc. by making the Pandavas his instruments to establish religion and destroy unrighteousness. Thereafter, the Yadav clan, which had increased the role, was also massacred with the help of a pestle in the name of the curse of the Brahmins. Aniruddha's son Vajra was anointed as the king. Subsequently, on the request of the Gods, Shri Hari himself, in the Prabhas Kshetra, finished his activities of the physical body and reached his abode. He is worshiped by the heavenly gods in Indralok and Brahmalok. Balram ji was the form of Sheshnag , hence he took shelter in heaven in the form of underworld. The immortal Lord Shri Hari is the aim of meditative people. After his death, the ocean left his personal residence and submerged the rest of Dwarkapuri in its waters. Arjun cremated the dead Yadavas and offered water for them and donated money etc. Lord Krishna went to Hastinapur with his queens, who were earlier Apsaras and had appeared in human form due to the curse of Ashtavakra. On the way, Bhils carrying sticks despised Arjun and snatched them all away. This was also possible only due to the curse of Ashtavakra . This caused great sorrow in Arjun's heart. Then when Maharishi Vyas did not console him, he decided that 'I had strength only by being close to Lord Krishna.' After coming to Hastinapur, he along with his brothers requested all this news from King Yudhishthir, who was following the subjects at that time. He said-

    'Brother! He is the bow, he is the arrow, he is the chariot and he is the horse, but without Lord Krishna, everything got destroyed just like the donation given to Ashrotriya. Hearing this, Dharmaraja Yudhishthir installed Parikshit on the kingdom.
    
    After this, considering the impermanence of the world, the wise king took Draupadi and his brothers along with him on the path of great departure towards the Himalayas. In that great path, Draupadi, Sahadev, Nakul, Arjun and Bhimsen fell one by one. The king became sombre due to this. Thereafter, he mounted the chariot brought by Indra and went to heaven along with his (divine form) brothers. They saw all the sons of Dhritarashtra, including Duryodhana, over there. After that, he also saw Lord Vasudev, who had come from his abode to show mercy on him. This made him very happy.`,
  },
];

export default Mahabharat;
